# Generated by Django 3.2.3 on 2021-07-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile',
            field=models.ImageField(default='default.jpg', upload_to='profile'),
        ),
    ]
